# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2" # Use this theme
plugins:
  # - jekyll-feed
  - jekyll-include-cache

# Site settings
#title: "Hafi"
email: "hafizh.iman.naufal@gmail.com"
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username: jekyll

# Enable sidebar on your site
sidebar:
  - nav

# Defaults for different page types
defaults:
  - scope:
      path: "" # Applies to all files
    values:
      sidebar: "nav"  # Enables sidebar globally
      layout: "single"  # Use layout that supports sidebar
      author_profile: true

# Author Information
author:
  name: "Hafizh Iman Naufal"
  avatar: "/assets/images/profile.jpg"  # Change to your photo path
  bio: "Data Engineer at NucleusBI" # Your brief bio (Markdown allowed)
  location: "Kuta, Bali, Indonesia"
  links:
    - label: " Resume" 
      icon: "fas fa-file-alt"
      url: "https://assets.glints.com/resume/0c2829ccb70a91a9e166cb537260a25f.pdf"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Hafizh-Iman-Naufal"  # Replace with your GitHub
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/hafizh-iman-naufal-655239195/"  # Replace with your LinkedIn
    - label: "Upwork"
      icon: "fab fa-fw fa-upwork"
      url: "https://www.upwork.com/freelancers/~018220f9a8c039a4e8?viewMode=1"  # Replace with your Upwork profile
    - label: "hafizh.iman.naufal@gmail.com"
      icon: "fas fa-fw fa-envelope"
      url: "hafizh.iman.naufal@gmail.com"  # Replace with your email
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/hafizh_iman"  # Replace with your Instagram profile



# Exclude unnecessary files and folders
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Other settings (Optional)
# Enable this section if you want to customize the layout further
# Uncomment and modify as needed
# markdown: kramdown
# permalink: /:categories/:title/
# social_links: true

# Language and Timezone settings (Optional)
# locale: en
# timezone: UTC

# Uncomment the below line if you need a specific config for posts or other collections
# collections:
#   posts:
#     output: true
#     permalink: /:year/:month/:day/:title/
